/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package muck.client;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MuckClientTest {
    @Test void testsRun() {
        //This test does not check anything useful  
        assertTrue(true);
    }
}
